version: '3.0'
services:
  db:
    image: postgres:9.6.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=majlis
      - POSTGRES_PASSWORD=sjrty12m43
      - POSTGRES_PORT=5432
    container_name: majlis-db-cont
    networks:
      - v1
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    restart: on-failure:10
    volumes:
      - /home/tshihad9/app/edesseri-majlis/static/:/app/static
    networks:
      - v1

  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6379:6379
    container_name: majlis-kvs-cont
    networks:
      - v1
    restart: always
networks:
  v1:

volumes:
  db-data: